#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     RightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
              _                                     _
   __ _ _   _| |_ ___  _ __  _   _ _ __  _ __   ___| |_
  / _` | | | | __/ _ \| '_ \| | | | '_ \| '_ \ / _ \ __|
 | (_| | |_| | || (_) | |_) | |_| | |_) | |_) |  __/ |_
  \__,_|\__,_|\__\___/| .__/ \__,_| .__/| .__/ \___|\__|
                      |_|         |_|   |_|
                      simplify autonomous programming.

  Version: 1.0.0 (Release)
  Updates: http://github.com/williamtdr/autopuppet

  Thanks for download autopuppet! Before you get started,
  there's a couple of files you'll want to modify to make
  sure everything's set up right for your robot:

    * puppet.c
        Check that the motor configuration at the top of
        this file is the same as your robot's. Go through
        the wizard at Robot -> Motors and Sensors setup if
        you need help, but make sure that your left wheel
        is called LeftDrive and your right wheel is called
        RightDrive.

    * config/settings.h (Optional)
        Here you can change which (if any) motors are
        reflected. This might need to be changed depending
        on the configuration of your robot. You can also
        change the joystick deadband. See that file for more
        details.

    Basic usage instructions can be found in README.md.

    This is not a completed program! The tracking algorithim
    is NOT ALL THAT ACCURATE at the moment and does not
    reproduce patterns well enough to be used as a production
    autonomous program for most teams. So please contribute
    code to help improve this program! Fork the repository,
    make your changes, then open a pull request on github.com.

    Thanks for using autopuppet!
*/

#include "JoystickDriver.c"
#include "system\globals.h"
#include "config\settings.h"
#include "system\strings.h"
#include "system\state.h"
#include "system\event.h"
#include "system\doTick.h"
#include "task\UpdateDisplayTask.h"
#include "task\UpdateJoystickTask.h"
#include "task\MainTask.h"